apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80         # external access port
      targetPort: 5000 # container port
      nodePort: 30080  # node port (optional - can be auto-assigned if omitted)

